export const data = {
  "userId": "",
  "id": "",
  "coverImage": "",
  "thumbnailImage": "",
  "effectImage": "none",
  "informationOfGroom":
  {
    "firstName": "",
    "middleName": "",
    "name": "",
    "isOldBrotherGroom": true,
    "codingRegion": "",
    "phoneNumberOfGroom": "",
    "firstFatherNameOfGroom": "",
    "middleFatherNameOfGroom": "",
    "fatherNameOfGroom": "",
    "phoneNumberOfFatherGroom": "",
    "isGoneFather": false,
    "firstMotherNameOfGroom": "",
    "middleMotherNameOfGroom": "",
    "motherNameOfGroom": "",
    "phoneNumberOfMotherGroom": "",
    "isGoneMother": false,
    "nameBankOfGroom": "",
    "ownerBankOfGroom": "",
    "bankOfNumberGroom": "",
    "qrCodeGroomLink": "",
    "nameBankOfFatherGroom": "",
    "ownerBankOfFatherGroom": "",
    "bankOfNumberFatherGroom": "",
    "qrCodeFatherGroomLink": "",
    "nameBankOfMotherGroom": "",
    "ownerBankOfMotherGroom": "",
    "bankOfNumberMotherGroom": "",
    "qrCodeMotherGroomLink": ""
  }
  ,
  "informationOfBride":
  {
    "firstName": "",
    "middleName": "",
    "name": "",
    "isOldBrotherBride": true,
    "codingRegion": "",
    "phoneNumberOfBride": "",
    "firstFatherNameOfBride": "",
    "middleFatherNameOfBride": "",
    "fatherNameOfBride": "",
    "phoneNumberOfFatherBride": "",
    "isGoneFatherBride": false,
    "firstMotherNameOfBride": "",
    "middleMotherNameOfBride": "",
    "motherNameOfBride": "",
    "phoneNumberOfMotherBride": "",
    "isGoneMotherOfBride": false,
    "nameBankOfBride": "",
    "ownerBankOfBride": "",
    "bankOfNumberBride": "",
    "qrCodeBrideLink": "",
    "nameBankOfFatherBride": "",
    "ownerBankOfFatherBride": "",
    "bankOfNumberFatherBride": "",
    "qrCodeFatherBrideLink": "",
    "nameBankOfMotherBride": "",
    "ownerBankOfMotherBride": "",
    "bankOfNumberMotherBride": "",
    "qrCodeMotherBrideLink": "",
    "isDisplayGonePeople": false,
  }
  ,
  "timeAndLocationOfWedding": {
    "dateOfEventWedding": "",
    "timeOfEventWedding": "",
    "locationOfWedding": "",
    "namelocationOfWedding": "",
    "mapDirectLink": "",
    "isDisplayCountDown": false,
    "contentOfCountDown": ""
  },
  "arraylist": [{
    "contentOfCountDown": "",
    "isUseVideo": false,
    "isUseEvent": false,
    "isUseDamNgo": false,
    "isUseBanking": false,
  }],
  "timeAndLocationOfEgagement": {
    "dateOfEventEgagement": "",
    "timeOfEventEgagement": "",
    "locationOfEgagement": ""
  },
  "timeAndLocationOfInterrogation": {
    "dateOfEventInterrogation": "",
    "timeOfEventInterrogation": "",
    "locationOfInterrogation": ""
  },
  "album": [],
  "albumLocal": [],
  "videoLink": "",
  "eventOfProgram": {
    "eventOfProgramEditOne": "Đón khách",
    "eventOfProgramEditTwo": "Làm lễ",
    "eventOfProgramEditThree": "Tiệc tối",
    "eventOfProgramEditFour": "Âm nhạc",
    "timeToWellcome": "",
    "timeToCelebrate": "",
    "timeToDinner": "",
    "timeToMusic": ""
  },
  "contentOfInvitation": '',
  "song": 1,
  "note": '',
  "isUseConfirm": false,
  "isUseGuestBook": false,
  "password": "",
  "contentGuestBook": "",
  "isEffectOfOpenning": false,
  "fontStyleOfTitle": {
    "id": 1,
    "name": "",
    "value": "pacifico"
  },
  "fontStyleOfContent": {
    "id": 1,
    "name": "",
    "value": "inter"
  },
  "styleBackground": {
    "id": 1,
    "name": "",
    "value": "none"
  },
  "backgroundColor": {
    "id": 1,
    "name": "",
    "value": "none"
  },
  "effectBackgroud": {
    "id": 1,
    "name": "",
    "value": "none"
  },
  "packageType": "",
  "anotherProduct": [],
  "codeInvite": "",
  "isPaid": false,
  "createTime": "",
  "updatedTime": "",
  "expiredTime": "",
  "confirmName": "",
  "confirmPhone": "",
  "confirmEmail": "",
  "confirmAddress": "",
  "confirmNote": "",
  "confirmProvince": "",
  "confirmDistrict": "",
  "confirmWardt": "",
  "totalAmount": "",
  "productId": "",
  "isUseVideo": false,
  "isUseEvent": false,
  "isUseDamNgo": false,
  "isUseBanking": false
}